In [197]:
import matplotlib.pyplot as plt
from netCDF4 import Dataset
import xarray as xr
import numpy as np
import pandas as pd
import numpy as np
import matplotlib as mpl


In [198]:
buoy = xr.open_dataset('http://goosbrasil.org:8080/pirata/B8s30w.nc')


In [199]:
buoy

<xarray.Dataset>
Dimensions:        (depth_s: 8, depth_t: 15, time: 5797)
Coordinates:
  * depth_s        (depth_s) float32 1.0 5.0 10.0 20.0 40.0 60.0 80.0 120.0
  * depth_t        (depth_t) float32 1.0 5.0 10.0 13.0 ... 180.0 300.0 500.0
  * time           (time) datetime64[ns] 2005-08-20T12:00:00 ... 2021-07-03T1...
Data variables:
    rad            (time) float32 ...
    salinity_q     (time, depth_s) float32 ...
    rh_q           (time) float32 ...
    salinity_s     (time, depth_s) float32 ...
    qsen_q         (time) float32 ...
    rh_s           (time) float32 ...
    rain_percent   (time) float32 ...
    bp_s           (time) float32 ...
    bp_q           (time) float32 ...
    temperature    (time, depth_t) float32 ...
    rad_s          (time) float32 ...
    lw             (time) float32 ...
    airt           (time) float32 ...
    rain_s         (time) float32 ...
    latitude       (time) float32 ...
    rain_q         (time) float32 ...
    rh             (time) float32 ...
    temperature_s  (time, depth_t) float32 ...
    rain_std       (time) float32 ...
    ws_s           (time) float32 ...
    lon_q          (time) float32 ...
    wd             (time) float32 ...
    qlat_q         (time) float32 ...
    ws_q           (time) float32 ...
    rain           (time) float32 ...
    rad_peak       (time) float32 ...
    bp             (time) float32 ...
    airt_s         (time) float32 ...
    airt_q         (time) float32 ...
    lat_q          (time) float32 ...
    qsen           (time) float32 ...
    rad_std        (time) float32 ...
    wd_q           (time) float32 ...
    wd_s           (time) float32 ...
    qlat           (time) float32 ...
    lw_s           (time) float32 ...
    lw_q           (time) float32 ...
    salinity_id    (time, depth_s) float32 ...
    rad_q          (time) float32 ...
    longitude      (time) float32 ...
    salinity       (time, depth_s) float32 ...
    ws             (time) float32 ...
    temperature_q  (time, depth_t) float32 ...
Attributes:
    comment:          These data were obtained from Pacific Marine Environmen...
    source:           Moored buoy from PIRATA
    history:          Created Tue Jul  6 12:08:35 2021
    description:      Buoy 8s30w
    missing_value:    -99999
    data_management:  SALT - Sea & Limno Technology
    institution:      GOOS-Brasil

In [200]:
buoy = buoy.where(buoy>0)

In [212]:
temp = buoy.variables['temperature'][:]
time = buoy.variables['time'][:]
depth = buoy.variables['depth_t'][:]

In [213]:
depth

<xarray.IndexVariable 'depth_t' (depth_t: 15)>
array([  1.,   5.,  10.,  13.,  23.,  30.,  40.,  60.,  80., 100., 120., 140.,
       180., 300., 500.], dtype=float32)
Attributes:
    units:      m
    long_name:  depth

In [214]:
#[X, Y] = np.meshgrid(np.linspace(min(time), max(time), n), np.linspace(min(depth), max(depth), n));
#Z = griddata(depth, time, temp, X, Y);

In [215]:
z= np.array(temp)
x1= np.array(time)
y1 = np.array(depth)



In [216]:
x1, y1 = np.meshgrid(time, depth)
z = z.reshape((len(depth),len(time)))

In [217]:
print(z.shape)
print(x1.shape)
print(y1.shape)

(15, 5797)
(15, 5797)
(15, 5797)


In [218]:
x1


array([['2005-08-20T12:00:00.000000000', '2005-08-21T12:00:00.000000000',
        '2005-08-22T12:00:00.000000000', ...,
        '2021-07-01T12:00:00.000000000', '2021-07-02T12:00:00.000000000',
        '2021-07-03T12:00:00.000000000'],
       ['2005-08-20T12:00:00.000000000', '2005-08-21T12:00:00.000000000',
        '2005-08-22T12:00:00.000000000', ...,
        '2021-07-01T12:00:00.000000000', '2021-07-02T12:00:00.000000000',
        '2021-07-03T12:00:00.000000000'],
       ['2005-08-20T12:00:00.000000000', '2005-08-21T12:00:00.000000000',
        '2005-08-22T12:00:00.000000000', ...,
        '2021-07-01T12:00:00.000000000', '2021-07-02T12:00:00.000000000',
        '2021-07-03T12:00:00.000000000'],
       ...,
       ['2005-08-20T12:00:00.000000000', '2005-08-21T12:00:00.000000000',
        '2005-08-22T12:00:00.000000000', ...,
        '2021-07-01T12:00:00.000000000', '2021-07-02T12:00:00.000000000',
        '2021-07-03T12:00:00.000000000'],
       ['2005-08-20T12:00:00.000000000', '20

In [219]:
y1

array([[  1.,   1.,   1., ...,   1.,   1.,   1.],
       [  5.,   5.,   5., ...,   5.,   5.,   5.],
       [ 10.,  10.,  10., ...,  10.,  10.,  10.],
       ...,
       [180., 180., 180., ..., 180., 180., 180.],
       [300., 300., 300., ..., 300., 300., 300.],
       [500., 500., 500., ..., 500., 500., 500.]], dtype=float32)

In [220]:
z

array([[26.49,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ..., 17.68, 13.08,  9.88],
       [ 7.29, 25.78,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan, 21.99, 18.8 , ..., 10.6 ,  7.71, 29.11],
       [  nan,   nan,   nan, ...,   nan, 28.91, 28.87],
       [27.02, 25.05, 23.1 , ..., 16.06,  9.87,  6.99]], dtype=float32)

In [250]:
plt.rcParams["figure.figsize"] = (10,5)

fig=plt.contourf(x1,y1,z, cmap='jet', vmin=24, vmax=29, extend= "both")
x1,x2,y1,y2 = plt.axis()
plt.axis((x1,x2,y1,y2))
plt.gca().invert_yaxis()
cbar = plt.colorbar()
plt.title('8s30w', fontsize=18)
plt.xlabel('Time', fontsize=18)
plt.ylabel('Depth', fontsize=18)
plt.show()



TypeError: Inputs x and y must be 1D or 2D.